spring.zipkin.service.name: 
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.22.0.5:8748/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://172.22.0.6:9200
      username: elastic
      password: changeme
server:
  port: 8080
spring: 
  cloud: 
    config: 
      allowOverride: true
